on:
  push:
    branches: [stable]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Get latest tag
        id: tag
        run: |
          git fetch --tags
          echo "tag=$(git tag --sort=-v:refname | tail -n 1)" >> $GITHUB_OUTPUT

      - name: Extract changelog
        id: changelog
        run: |
          version=${{ steps.tag.outputs.tag }}
          awk "/^## \[\Q$version\E\]/ {print_flag=1; next} /^## \[/ && print_flag { exit } print_flag" CHANGELOG.md > release_body.md
          echo "log<<EOF" >> $GITHUB_OUTPUT
          cat release_body.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: |
          mkdir dist 
          GOOS=linux GOARCH=amd64 go build -o dist/govault-linux ./cmd/govault
          GOOS=windows GOARCH=amd64 go build -o dist/govault-windows.exe ./cmd/govault

      - name: Upload binaries
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Govault ${{ steps.tag.outputs.tag }}
          body: ${{ steps.changelog.outputs.log }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
