on:
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    if: |
      (github.event_name == 'pull_request' && startsWith(github.head_ref, 'release/')) ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Get latest tag
        id: tag
        run: |
          git fetch --tags
          latest_tag=$(git tag --sort-v:refname | grep '^v' | tail -n 1)
          echo "Latest tag: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Read changelog
        id: changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.tag.outputs.tag }}
          path: ./CHANGELOG.md

      - name: Build binaries
        run: |
          mkdir dist 
          GOOS=linux GOARCH=amd64 go build -o dist/govault-linux ./cmd/govault
          GOOS=windows GOARCH=amd64 go build -o dist/govault-windows.exe ./cmd/govault

      - name: Upload binaries
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Govault ${{ steps.tag.outputs.tag }}
          body: ${{ steps.changelog.outputs.changes }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
